---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: stop docker container named insure-me
    command: sudo docker stop insure-me

  - name: remove docker container named insure-me
    command: sudo docker rm insure-me

  - name: deploy insureme application
    command: sudo docker run --rm -itd -p 8081:8081 --name insure-me manofoever/insurance-project:1.0
